name: fapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  shared_preferences: ^2.5.1
  http: ^1.1.0
  flutter_native_splash: ^2.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/launcher.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/icons/launcher.png
    background_color: "#006C14"
    theme_color: "#006C14"
  windows:
    generate: true
    image_path: assets/icons/launcher.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/icons/launcher.png

flutter_native_splash:
  color: "#006C14"
  image: assets/icons/splash.png
  branding_bottom_padding: 24
  color_dark: "#121212"
  image_dark: assets/icons/splash.png

  android_12:
    image: assets/icons/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/splash.png
    icon_background_color_dark: "#121212"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
