name: fapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  shared_preferences: ^2.5.1
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/launcher.png
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/icons/launcher.png
    background_color: "#006C14"
    theme_color: "#006C14"
  windows:
    generate: true
    image_path: assets/icons/launcher.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/icons/launcher.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
